-- Query de Diagnóstico: Identificar onde estão sendo perdidas as 110 cotações
-- Executa cada filtro separadamente para ver o impacto

-- 1. Total de cotações no período (baseline: deveria dar 629)
SELECT 
  'Total Baseline' as tipo,
  COUNT(*) as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'

UNION ALL

-- 2. Cotações que têm pelo menos um QUOTATION_ITEM
SELECT 
  'Com QUOTATION_ITEM' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'

UNION ALL

-- 3. Cotações que têm pelo menos um QUOTATION_ITEM_BRAND
SELECT 
  'Com QUOTATION_ITEM_BRAND' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'

UNION ALL

-- 4. Com filtro: NEGOTIATED_PRICE IS NOT NULL
SELECT 
  'Com NEGOTIATED_PRICE' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'
  AND qib."NEGOTIATED_PRICE" IS NOT NULL

UNION ALL

-- 5. Com filtro: ID_PROVIDER IS NOT NULL
SELECT 
  'Com ID_PROVIDER' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'
  AND qib."NEGOTIATED_PRICE" IS NOT NULL
  AND qib."ID_PROVIDER" IS NOT NULL

UNION ALL

-- 6. Com filtro: TOTALIZER_LAST_ITEM_PRICE IS NOT NULL
SELECT 
  'Com TOTALIZER_LAST_ITEM_PRICE NOT NULL' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'
  AND qib."NEGOTIATED_PRICE" IS NOT NULL
  AND qib."ID_PROVIDER" IS NOT NULL
  AND qib."TOTALIZER_LAST_ITEM_PRICE" IS NOT NULL

UNION ALL

-- 7. Query Final Completa (deveria dar 519)
SELECT 
  'Query N8N Completa' as tipo,
  COUNT(DISTINCT qp."process_ptr_id") as quantidade
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "OFFICE_GROUP" AS og ON qp."ID_FAVORED_CUSTOMER_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE og."ID_OFFICE_GROUP" = 114
  AND qp."DTT_FINISHED" >= '2025-07-01'
  AND qp."DTT_FINISHED" < '2025-08-01'
  AND qib."NEGOTIATED_PRICE" IS NOT NULL
  AND qib."ID_PROVIDER" IS NOT NULL
  AND qib."TOTALIZER_LAST_ITEM_PRICE" IS NOT NULL
  AND qib."TOTALIZER_LAST_ITEM_PRICE" > 0

ORDER BY quantidade DESC;
