-- DIAGNÓSTICO COMPLETO: 519 vs 629 COTAÇÕES
-- Análise detalhada para encontrar as 110 cotações que faltam

-- 1️⃣ TOTAL GERAL DE COTAÇÕES (sem filtros - deve dar ~629)
SELECT 
  'TOTAL_GERAL' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_PROCESS" AS qp
WHERE qp."DTT_FINISHED" IS NOT NULL;

-- 2️⃣ COTAÇÕES NO PERÍODO (2025-07-01 a 2025-07-31)
SELECT 
  'PERIODO_JULHO_2025' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_PROCESS" AS qp
WHERE qp."DTT_FINISHED" IS NOT NULL
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31';

-- 3️⃣ COTAÇÕES NO GRUPO 114
SELECT 
  'GRUPO_114' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" 
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE qp."DTT_FINISHED" IS NOT NULL
  AND og."ID_OFFICE_GROUP" = 114;

-- 4️⃣ COTAÇÕES COM PERÍODO + GRUPO 114
SELECT 
  'PERIODO_E_GRUPO_114' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" 
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE qp."DTT_FINISHED" IS NOT NULL
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114;

-- 5️⃣ COTAÇÕES QUE PASSAM PELOS FILTROS DA QUERY COMPLEXA (deve dar 519)
SELECT 
  'COM_FILTROS_COMPLEXOS' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_ITEM_BRAND" AS qib
JOIN "QUOTATION_ITEM" AS qi ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
JOIN "QUOTATION_PROCESS" AS qp ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" AND cust_co."PROFILE" = 'CUSTOMER'
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE qib."NEGOTIATED_PRICE" IS NOT NULL
  AND qib."ID_PROVIDER" IS NOT NULL
  AND qib."TOTALIZER_LAST_ITEM_PRICE" IS NOT NULL
  AND qib."TOTALIZER_LAST_ITEM_PRICE" > 0
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114;

-- 6️⃣ ANÁLISE DOS FILTROS QUE ELIMINAM COTAÇÕES
SELECT 
  'SEM_NEGOTIATED_PRICE' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as cotacoes_eliminadas
FROM "QUOTATION_ITEM_BRAND" AS qib
JOIN "QUOTATION_ITEM" AS qi ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
JOIN "QUOTATION_PROCESS" AS qp ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" AND cust_co."PROFILE" = 'CUSTOMER'
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE qib."NEGOTIATED_PRICE" IS NULL
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114

UNION ALL

SELECT 
  'SEM_PROVIDER' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as cotacoes_eliminadas
FROM "QUOTATION_ITEM_BRAND" AS qib
JOIN "QUOTATION_ITEM" AS qi ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
JOIN "QUOTATION_PROCESS" AS qp ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" AND cust_co."PROFILE" = 'CUSTOMER'
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE qib."ID_PROVIDER" IS NULL
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114

UNION ALL

SELECT 
  'SEM_LAST_PRICE_OU_ZERO' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as cotacoes_eliminadas
FROM "QUOTATION_ITEM_BRAND" AS qib
JOIN "QUOTATION_ITEM" AS qi ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
JOIN "QUOTATION_PROCESS" AS qp ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" AND cust_co."PROFILE" = 'CUSTOMER'
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
WHERE (qib."TOTALIZER_LAST_ITEM_PRICE" IS NULL OR qib."TOTALIZER_LAST_ITEM_PRICE" <= 0)
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114;

-- 7️⃣ VERIFICAR SE EXISTEM COTAÇÕES SEM ITENS/BRANDS
SELECT 
  'COTACOES_SEM_ITEMS_BRANDS' as categoria,
  COUNT(DISTINCT qp."process_ptr_id") as total_cotacoes
FROM "QUOTATION_PROCESS" AS qp
LEFT JOIN "COMPANY" AS cust_co ON qp."ID_FAVORED_CUSTOMER" = cust_co."ID_COMPANY" AND cust_co."PROFILE" = 'CUSTOMER'
LEFT JOIN "OFFICE_GROUP" AS og ON cust_co."ID_OFFICE_GROUP" = og."ID_OFFICE_GROUP"
LEFT JOIN "QUOTATION_ITEM" AS qi ON qi."ID_QUOTATION_PROCESS" = qp."process_ptr_id"
LEFT JOIN "QUOTATION_ITEM_BRAND" AS qib ON qib."ID_QUOTATION_ITEM" = qi."ID_QUOTATION_ITEM"
WHERE qp."DTT_FINISHED" IS NOT NULL
  AND qp."DTT_FINISHED"::date >= '2025-07-01'
  AND qp."DTT_FINISHED"::date <= '2025-07-31'
  AND og."ID_OFFICE_GROUP" = 114
  AND (qi."ID_QUOTATION_ITEM" IS NULL OR qib."ID_QUOTATION_ITEM_BRAND" IS NULL);
